language: php
php:
  - 5.5
  - 5.4
  - 5.3

env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"

before_script:
  - sh -c 'cp composer.json composer.json.orig'
  - sh -c 'sed "s/\(\"symfony\/framework-bundle\":\) \".*\"/\1 \"${SYMFONY_VERSION}\"/" composer.json.orig > composer.json'
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script: phpunit